[project]
name = "nemetron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "fastapi>=0.138.1",
    "librosa>=0.11.0",
    "python-dotenv>=1.2.2",
    "sounddevice>=0.5.5",
    "soundfile>=0.14.0",
    "streamlit>=1.58.0",
    "torch>=2.0.0",
    "tqdm>=4.68.3",
    "transformers",
    "uvicorn>=0.49.0",
    "websockets>=16.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
transformers = { git = "https://github.com/huggingface/transformers" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
