[project]
name = "youtube-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.136.3",
    "openai>=2.38.0",
    "python-dotenv>=1.2.2",
    "tqdm>=4.67.3",
    "uvicorn>=0.47.0",
    "youtube-transcript-api>=1.2.4",
]
